### ISSUE TITLE
Branches to be renamed in Phoebe ntuples

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/plot_scripts#5]
As @yipengsun suggested, we can use this issue to keep a list of the variables that we use from Phoebe's ntuples, what name we'd like them to have, and any explanation of the variable as we find it. Let us use the format that [babymaker](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/b2683f62e6b6f1c55c56f2bf56c6ed4fa57fe941/run2-b2D0MuXB2DMuForTauMuLine/postprocess/Dst-triggering-stripping.yml#L13-L45) will use, for instance

```
FFweight: w_ff
# Some MC weight, need to find out what it contains
mcWeight: w_mc
# Missing mass squared in GeV
m_nu1: mm2
```

My general conventions for branch naming, still to be discussed, are:
- As short as possible
- All lowercase
- Separate words with `_`
- Weights start with `w_`

Particle names are defined in [reco_Dst.py](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/b2683f62e6b6f1c55c56f2bf56c6ed4fa57fe941/run2-b2D0MuXB2DMuForTauMuLine/reco_Dst.py#L634-L641). For instance, Phoebe's `Y_P` would be `b0_p` for us, or `pislow_PT` would be `spi_pt`.

Hum, I wonder if we should rename the slow pion `pis_` so that it is easier to search in the string.

**Comment by afernez** [comment]
This comment will need to be edited. I'll note the variable types (notably, most variables are doubles, but many are really acting as booleans or ints). I'll also make notes of relevant **lines in Phoebe's AddB.C** defining variables, if this is available. I'll group variables based on whether they were used to select components, used for cuts/to select control samples, or used in weight calculations; these will inevitably intersect, and I'll just write each variable once. Of course, anyone is free to edit the names I choose for the variables or my (mis)understanding of its meaning.

Selecting components
```
DstIDprod: dst_id_prod   # =D0_ID*piminus_ID?, double, 2534
IDprod: id_prod   # =D0_ID*muplus_ID?, double, 2533
muPID: mu_pid   # (is MC and correct TRUEID) or (isMuon and PIDmu > 2)?, float, 2540
flagDstSB: flag_dst_sb   # part of D* mass sideband, double, 4296 matches line 2305 in redoHistos_Dst.C
isData: is_data   # event is data, double, 2439
totweight: w_tot   # weight used for comb bkgd and misID, double, affected by many lines
flagtaumu: flag_tau   # MC semi-tauonic B decay, double, 2743-2746
JustDst: just_dst   # D* from B, not D**, double, 2814
DstOk: dst_ok   # ?, double, 2547 (with comment about variable use)
Btype: b_type   # type of B meson (B0==511, B-==521, B0s==531), int
flagBmu: flag_mu   # MC semi-muonic B decay, double, 2742-2747
Y_BKGCAT: b_bkg_cat   # ?, int
Dststtype: dss_type   # type of D** (D1+==10413, D10==10423, D2*+==415, D2*0==425, Ds2*==435, D1'+==20413, D1'0==20423, Ds1'==10433?), int, 2822-2831
ishigher: is_2pi   # 2S D** instead of 1P D**? Phoebe says checks if 2pi cocktail member, bool, 3255-3277
mm_mom: mm_dst_mom   # missing mass between D* and mother?, double, 3136-3142
Dst_2010_minus_MC_MOTHER_ID: dst_mom_id  # ID of charged D* mother, int
flagTauonicD: flag_two_d_tau   # semitauonic with tau from 431 (what particle is this?) and assumedly with two D mesons, double, 2791
flagDoubleD: flag_two_d_mu   #  MC semimuonic with mu from 411 or 421 or 431 and two D mesons, double, 2757
```

Control Sample Selection, Cuts
```
TODO
```

Weight calculations
```
TODO
```

Other
```
ISOnum: iso_num   # ?

```

**Comment by yipengsun** [comment]
I've added all **Selecting components** in our step 2 ntuples.

**Comment by yipengsun** [comment]
Related issue: umd-lhcb/lhcb-ntuples-gen#50.

**Comment by yipengsun** [comment]
This has been implemented in `lhcb-ntuple-gen`. Closed.
